= Banking accounts model

Goal of this application is a tool to apply a personal accounts model for finance management. Based on this model, recurring pre-configured transactions can be executed easily, e.g. on a monthly basis. The transactions can either be absolute or relative, e.g. 10% of your monthly income.

== Example config file

Let's assume we have the following remittance jobs:

* Transfer 10% of your income to savings - from: DE12345678901234567890 to: DE09876543210987654321
* Transfer 15% of your income to the credit card - from: DE12345678901234567890 to: 1111pass:[********]1111
* Transfer 500 EUR rent to your landlord - from: DE12345678901234567890 to: DE09876543210987654321

.job.json
[source,json]
----
{
    "dispatch": [
        {
            "Name": "Savings",
            "Share": 10,
            "SourceAccount": "DE12345678901234567890",
            "TargetAccount": "DE09876543210987654321",
            "Remittee": "Mickey Mouse"
        },
        {
            "Name": "Creditcard deposit",
            "Share": 15,
            "SourceAccount": "DE12345678901234567890",
            "TargetAccount": "1111********1111"
        },
        {
            "Name": "House rent",
            "ShareValue": 500,
            "SourceAccount": "DE12345678901234567890",
            "TargetAccount": "DE09876543210987654321",
            "Remittee": "Mickey Mouse",
            "Description": "Rent May 2019"
        }
    ]
}
----

.Table 'job.json' field description
|===
|Field |Description

|_Name_
|Transaction name.

|_Share_ or _ShareValue_
|Transaction amount. Either absolute EUR value (_ShareValue_) or percentage of income (_Share_). If _Share_ is set, the application asks for the income at the beginning.

|_SourceAccount_
|Either an IBAN or credit card within your DKB account. This account will be debited. +
Format IBAN: <Country code><20 digit iban number> - no spaces allowed +
Format credit card: <4 digits><8 asterisks><4 digits> - no spaces allowed +
If credit card is chosen, the associated checking account must be selected in _TargetAccount_, because credit cards are strictly bound to a single checking account within DKB. To find out, which checking account is the correct one, login to your DKB banking and try to initiate a transaction to your credit card.

|_TargetAccount_
|Either an IBAN or credit card. This account will be credited.
Format IBAN: <Country code><20 digit iban number> - no spaces allowed +
Format credit card: <4 digits><8 asterisks><4 digits> - no spaces allowed +
If credit card is chosen, the associated checking account must be selected in _SourceAccount_, because credit cards are strictly bound to a single checking account within DKB. To find out, which checking account is the correct one, login to your DKB banking and try to initiate a transaction to your credit card.

|_Remittee_
|Name of the credited person or company. +
This field is mandatory for transactions to other banks only, otherwise will be ignored.

|_Description_
|Transaction purpose line. +
This field can be set, if the target account is a local or other banks IBAN, otherwise will be ignored. +
*REMARK: Omit this field for recurring transactions. Some banks, like DKB, reject transactions, if the purpose line has been used in other transactions before. If the field is not set, the purpose line is auto-generated using the 'Name' field and current timestamp.*
|===

== How to use
=== Prerequesites
* Python3
** Packages: pip install readchar robobrowser lxml prettytable

=== Execute
After adding a 'job.json' config file (see above), just run:

`python3 dispatchIncome`

== Out of scope

* BIC support: Currently, the capability to transfer money to international bank accounts (where BIC is needed) is not supported.

